apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapp
  namespace: billingns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapp
  template:
    metadata:
      labels:
        app: rapp
    spec:
      containers:
      - name: rapp
        image: rapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rapp-service
  namespace: billingns
spec:
  selector:
    app: rapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31001
  type: NodePort

 
# selector:
#   app: rapp
# ports:
# - port: 7001
#   targetPort: 3000
# type: ClusterIP