apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: billingns
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.4
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306 # Changed to MySQL's default port
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-windows-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: billingns
spec:
  type: NodePort
  selector: # Uncommented to ensure routing works
    app: mysql
  ports:
  - port: 3306 
    targetPort: 3306 # Matches containerPort
    nodePort: 31002 # Fixed capitalization from NodePort to nodePort