apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-helloworld
spec:
  selector:
    matchLabels:
      app: nodejs-helloworld
  template:
    metadata:
      labels:
        app: nodejs-helloworld
    spec:
      containers:
      - name: nodejs-helloworld
        image: nodejs-helloworld:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-hellowold-service
spec:
  selector:
    app: nodejs-helloworld
  ports:
  - nodePort: 31000
    #port is where service is exposed outside of cluster
    port: 4001
    #target port is where servce is running in container.
    targetPort: 3000 

  type: NodePort